//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.ClassAttendees = new HashSet<ClassAttendee>();
            this.ClassSessions = new HashSet<ClassSession>();
            this.ClassSignInSheets = new HashSet<ClassSignInSheet>();
            this.CoursesTakens = new HashSet<CoursesTaken>();
            this.CoursesTakenHistories = new HashSet<CoursesTakenHistory>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<System.DateTime> ScheduledStartDate { get; set; }
        public Nullable<System.DateTime> ScheduledEndDate { get; set; }
        public Nullable<System.DateTime> ScheduledStartTime { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<byte> RegionID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string InstructorNotes { get; set; }
        public Nullable<int> LocationCodeID { get; set; }
        public Nullable<bool> Certificates { get; set; }
        public Nullable<System.DateTime> ScheduledEndTime { get; set; }
        public Nullable<bool> PocketCards { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public bool Completed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassAttendee> ClassAttendees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassSession> ClassSessions { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual LocationCode LocationCode { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassSignInSheet> ClassSignInSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesTaken> CoursesTakens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesTakenHistory> CoursesTakenHistories { get; set; }
    }
}
