//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.ClassSessions = new HashSet<ClassSession>();
            this.CoursesTakens = new HashSet<CoursesTaken>();
            this.CoursesTakenHistories = new HashSet<CoursesTakenHistory>();
        }
    
        public int CourseID { get; set; }
        public string CourseDescription { get; set; }
        public Nullable<short> CertificationAgencyID { get; set; }
        public string CertAgency { get; set; }
        public Nullable<short> CourseLength { get; set; }
        public string CourseLengthUnit { get; set; }
        public Nullable<byte> RenewalPeriodMonths { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string CertificateDescription { get; set; }
        public string CertificateSubDescription { get; set; }
        public Nullable<bool> PocketCards { get; set; }
    
        public virtual CertificationAgency CertificationAgency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassSession> ClassSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesTaken> CoursesTakens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesTakenHistory> CoursesTakenHistories { get; set; }
    }
}
