//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_CTL_TS__COMPANY_INFORMATION_BAD
    {
        public string DBID { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address_1 { get; set; }
        public string Company_Address_2 { get; set; }
        public string Company_City { get; set; }
        public string Company_State { get; set; }
        public string Company_Zip_Code { get; set; }
        public string Company_Phone { get; set; }
        public string Company_Fax { get; set; }
        public string Company_Email { get; set; }
        public string Company_Web_Address { get; set; }
    }
}
