//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_PRM_MASTER__EMPLOYEE1
    {
        public string DBID { get; set; }
        public string Employee { get; set; }
        public string Employee_Name { get; set; }
        public string Title { get; set; }
        public string Occupation { get; set; }
        public string Country { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string Foreign_State { get; set; }
        public string Foreign_Postal_Code { get; set; }
        public string Email_address { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<System.DateTime> Hire_Date { get; set; }
        public bool HIRE_Act_Qualified { get; set; }
        public Nullable<System.DateTime> Rehire_Date { get; set; }
        public Nullable<System.DateTime> Termination_Date { get; set; }
        public string Operator_Stamp { get; set; }
        public Nullable<System.DateTime> Date_Stamp { get; set; }
        public string Time_Stamp { get; set; }
        public string Employee_File_Links { get; set; }
    }
}
