//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCertification
    {
        public int JobCertificationID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> CourseID { get; set; }
    }
}
