//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourseBAD
    {
        public int CourseID { get; set; }
        public string CourseDescription { get; set; }
        public string CertAgency { get; set; }
        public Nullable<byte> CourseLength { get; set; }
        public string CourseLengthUnit { get; set; }
        public Nullable<byte> RenewalPeriodYears { get; set; }
        public string CertificateTitle { get; set; }
        public string CertificateDetail { get; set; }
    }
}
