//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeCourseBAD
    {
        public int RecordID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public bool Required { get; set; }
        public Nullable<System.DateTime> CertDate { get; set; }
    }
}
