//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCoursesTaken
    {
        public int CoursesTakenID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string DBID { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<bool> Expired { get; set; }
        public Nullable<int> LocationCodeID { get; set; }
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
    }
}
