//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCoursesTakenOLD
    {
        public string EmployeeLastName { get; set; }
        public string EmployeeFirstName { get; set; }
        public int CoursesTakenID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string CourseDescription { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> CertificationDate { get; set; }
        public bool Required { get; set; }
        public string CertificationAgency { get; set; }
        public Nullable<short> CertificationAgencyID { get; set; }
        public string InstructorName { get; set; }
        public Nullable<int> InstructorID { get; set; }
    }
}
