//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyTraining.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGetEmployee
    {
        public int EmployeeID { get; set; }
        public string TLEmployee { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public Nullable<byte> EmployeeStatusID { get; set; }
        public string DBID { get; set; }
        public string Occupation { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<short> PositionId { get; set; }
        public Nullable<System.DateTime> RehireDate { get; set; }
        public string EmployeeNotes { get; set; }
        public Nullable<System.DateTime> TLModifiedDate { get; set; }
        public string TLEmployeeName { get; set; }
        public Nullable<byte> Deleted { get; set; }
        public string LocationCode { get; set; }
        public Nullable<int> LocationCodeID { get; set; }
        public string EmployeeName { get; set; }
    }
}
